// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContact(arg1, arg2, arg3, arg4) {
  return window['go']['manager']['Manager']['AddContact'](arg1, arg2, arg3, arg4);
}

export function AddSharedContainer(arg1) {
  return window['go']['manager']['Manager']['AddSharedContainer'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['manager']['Manager']['CopyToClipboard'](arg1);
}

export function CreateContainer(arg1, arg2, arg3) {
  return window['go']['manager']['Manager']['CreateContainer'](arg1, arg2, arg3);
}

export function DeleteContact(arg1) {
  return window['go']['manager']['Manager']['DeleteContact'](arg1);
}

export function DeleteContainer(arg1) {
  return window['go']['manager']['Manager']['DeleteContainer'](arg1);
}

export function DeleteObject(arg1, arg2) {
  return window['go']['manager']['Manager']['DeleteObject'](arg1, arg2);
}

export function Download(arg1, arg2, arg3) {
  return window['go']['manager']['Manager']['Download'](arg1, arg2, arg3);
}

export function ForceSync() {
  return window['go']['manager']['Manager']['ForceSync']();
}

export function Get(arg1, arg2, arg3, arg4) {
  return window['go']['manager']['Manager']['Get'](arg1, arg2, arg3, arg4);
}

export function GetAccountInformation() {
  return window['go']['manager']['Manager']['GetAccountInformation']();
}

export function GetObjectMetaData(arg1, arg2) {
  return window['go']['manager']['Manager']['GetObjectMetaData'](arg1, arg2);
}

export function GetVersion() {
  return window['go']['manager']['Manager']['GetVersion']();
}

export function ListContainerIDs() {
  return window['go']['manager']['Manager']['ListContainerIDs']();
}

export function ListContainerObjects(arg1, arg2) {
  return window['go']['manager']['Manager']['ListContainerObjects'](arg1, arg2);
}

export function ListContainers(arg1) {
  return window['go']['manager']['Manager']['ListContainers'](arg1);
}

export function ListSharedContainerObjects(arg1, arg2) {
  return window['go']['manager']['Manager']['ListSharedContainerObjects'](arg1, arg2);
}

export function ListSharedContainers() {
  return window['go']['manager']['Manager']['ListSharedContainers']();
}

export function LoadWallet(arg1) {
  return window['go']['manager']['Manager']['LoadWallet'](arg1);
}

export function LoadWalletWithPath(arg1, arg2) {
  return window['go']['manager']['Manager']['LoadWalletWithPath'](arg1, arg2);
}

export function MakeNotification(arg1) {
  return window['go']['manager']['Manager']['MakeNotification'](arg1);
}

export function MakeToast(arg1) {
  return window['go']['manager']['Manager']['MakeToast'](arg1);
}

export function MarkAllNotificationsRead() {
  return window['go']['manager']['Manager']['MarkAllNotificationsRead']();
}

export function MarkNotificationRead(arg1) {
  return window['go']['manager']['Manager']['MarkNotificationRead'](arg1);
}

export function NetworkChangeNotification() {
  return window['go']['manager']['Manager']['NetworkChangeNotification']();
}

export function NewListReadOnlyContainerContents(arg1) {
  return window['go']['manager']['Manager']['NewListReadOnlyContainerContents'](arg1);
}

export function NewWallet(arg1) {
  return window['go']['manager']['Manager']['NewWallet'](arg1);
}

export function Notifications() {
  return window['go']['manager']['Manager']['Notifications']();
}

export function OpenInDefaultBrowser(arg1) {
  return window['go']['manager']['Manager']['OpenInDefaultBrowser'](arg1);
}

export function Pool() {
  return window['go']['manager']['Manager']['Pool']();
}

export function RecentWallets() {
  return window['go']['manager']['Manager']['RecentWallets']();
}

export function RemoveSharedContainer(arg1) {
  return window['go']['manager']['Manager']['RemoveSharedContainer'](arg1);
}

export function RestrictContainer(arg1, arg2) {
  return window['go']['manager']['Manager']['RestrictContainer'](arg1, arg2);
}

export function RetrieveContactByWalletAddress(arg1) {
  return window['go']['manager']['Manager']['RetrieveContactByWalletAddress'](arg1);
}

export function RetrieveContacts() {
  return window['go']['manager']['Manager']['RetrieveContacts']();
}

export function SendSignal(arg1, arg2) {
  return window['go']['manager']['Manager']['SendSignal'](arg1, arg2);
}

export function SetProgressPercentage(arg1) {
  return window['go']['manager']['Manager']['SetProgressPercentage'](arg1);
}

export function SetSelectedNetwork(arg1) {
  return window['go']['manager']['Manager']['SetSelectedNetwork'](arg1);
}

export function SetWalletDebugging(arg1, arg2) {
  return window['go']['manager']['Manager']['SetWalletDebugging'](arg1, arg2);
}

export function TopUpNeoWallet(arg1) {
  return window['go']['manager']['Manager']['TopUpNeoWallet'](arg1);
}

export function TransferToken(arg1, arg2) {
  return window['go']['manager']['Manager']['TransferToken'](arg1, arg2);
}

export function UnlockWallet() {
  return window['go']['manager']['Manager']['UnlockWallet']();
}

export function Upload(arg1, arg2) {
  return window['go']['manager']['Manager']['Upload'](arg1, arg2);
}

export function UploadObject(arg1, arg2, arg3) {
  return window['go']['manager']['Manager']['UploadObject'](arg1, arg2, arg3);
}
