definitions:
  localserve.HTTPClientError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  localserve.HTTPServerError:
    properties:
      code:
        example: 502
        type: integer
      message:
        example: status server error
        type: string
    type: object
info:
  contact: {}
paths: {}
swagger: "2.0"
