name: Build for linux
on:
  workflow_dispatch:
  # This Action only starts when you go to Actions and manually run the workflow.
  push:
# see here for variables
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: linux-os, platform: linux/amd64, os: ubuntu-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.1
        env:
          CI: false
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}