name: Create Release
on:
  workflow_dispatch:
  # This Action only starts when you go to Actions and manually run the workflow.
  push:
#    branches:
#      - master #don't run when master is pushed so doesn't mess up releases
#    # Sequence of patterns matched against refs/tags
#    tags:
#      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# see here for variables
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: install frontend
        run: |
          cd frontend && npm install
      - name: build frontend macOS
        run: |
          cd frontend && CI= npm run build
      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      # linux
      - name: Build for linux
        run: |
          /home/runner/go/bin/wails build
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-binaries
          path: build/bin/*