name: Get Semver
on:
  push:
    branches:
      - semver
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

# see here for variables
jobs:
  package:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest]
        go-version: [1.18]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Get version
        id: semver
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
          tag: ${{ github.ref }}
      - name: Print version
        needs: semver
        run:
          echo ${{ steps.semver.outputs.prefixed }}