name: Create Release
on:
  workflow_dispatch:
  # This Action only starts when you go to Actions and manually run the workflow.
  push:
#    branches:
      - semver #don't run when master is pushed so doesn't mess up releases
#    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# see here for variables
jobs:
  package:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest]
        go-version: [1.18]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Get version
        id: semver
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
          tag: ${{ github.ref }}